"""Updated model relationships

Revision ID: 1dde82ff9555
Revises: de24ca78e63d
Create Date: 2023-11-19 15:04:12.736980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dde82ff9555'
down_revision = 'de24ca78e63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
