"""Updated modelled relationships

Revision ID: 58f5facb1e7d
Revises: f060c3a0f47c
Create Date: 2023-11-19 15:37:13.951394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f5facb1e7d'
down_revision = 'f060c3a0f47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
