"""Updated model-id relationships

Revision ID: 6773719e3c54
Revises: 1dde82ff9555
Create Date: 2023-11-19 15:23:25.294379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6773719e3c54'
down_revision = '1dde82ff9555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
