"""Updated model relationships

Revision ID: de24ca78e63d
Revises: e893c515d77e
Create Date: 2023-11-19 14:42:40.675838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de24ca78e63d'
down_revision = 'e893c515d77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
