"""Updated models

Revision ID: e893c515d77e
Revises: bf415f50156f
Create Date: 2023-11-19 14:33:54.567996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e893c515d77e'
down_revision = 'bf415f50156f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
