"""Updated model-id relationships

Revision ID: f060c3a0f47c
Revises: 5d2dc22240db
Create Date: 2023-11-19 15:36:14.275465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f060c3a0f47c'
down_revision = '5d2dc22240db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
